jobs:
- job: linux
  pool:
    vmImage: 'ubuntu-16.04'
  steps:
  - script: make test

- job: macos
  pool:
    vmImage: 'macos-10.13'
  steps:
  - script: make test

- job: windows
  pool:
    vmImage: 'vs2017-win2016'
  steps:
  - script: |
    "C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\VC\Auxiliary\Build\vcvarsall.bat" x64
    build.bat
    displayName: Build it
  - script: python.exe test.py
    displayName: Run tests